print("Please no swearing and/or inappropriate words for a classroom")

your_name = input("What is your name? ")
person = input("Give me a name of person")
adjective = input("Adjective Time! Give me one!")
verb = input("Can you give me a verb?")
verb2 = input("Can you give me a second verb?")
noun = input("I'm gonna need a noun now.")
noun2 = input("I'm gonna need another noun")
plural_noun = input("I need a plural noun next")
verb3 = input("Can I get a verb?")
noun3 = input("I need a third noun")
plural_noun2 = input("I need a new plural noun")
verb4 = input("I need a fourth verb now...")
adjective2 = input("I need a new adjective")
person2 = input("Give me another person name")
adjective3 = input("I need a third adjective")
verb5 = input("Wow, I need a fifth verb!")
character = input("Give me a character from a game, book or show")
character2 = input("Give me another character from a game, book or show")
character3 = input("It's a triple wammy! Give me another character from a game, book or show")
noun4 = input("Time for a new noun")
noun5 = input("Can I get another noun?")
noun6 = input("Tic-tac-toe! 3 nouns in a row")
noun7 = input("...I need another noun...")
noun8 = input("Another noun.... something needs to break this streak")
adjective4 = input("I need an adjective now (Finally! Something that isn't a noun)")
adjective5 = input("I need another adjective now")
character4 = input("Give me a character from a game, book or show")
adjective6 = input("New adjective! Go!")
character5 = input("Give me a new character from a game, book or show")
character6 = input("I need a new character now")
game = input("Give me some kind of video game")
number = input("Give me a number! Large or small, it doesn't matter!")
print()
print("Time for the Mad Lib!")
print()
print()
print()
print("The New Super Smash Bros")
print("Super Smash Bros is a game made by %s in which %s characters %s (with) each other." % (person, adjective, verb))
print("The objective is to %s each other off the %s." % (verb2, noun))
print("There are many modes like %s battle where you fight to make characters lose %s" % (noun2, plural_noun))
print("or %s battle where you %s your opponents’ %s to defeat them." % (noun3, verb3, plural_noun2))
print("Sometimes there is a story mode, last time you had to %s the %s %s," % (verb4, adjective2, person2))
print(", it was the most %s way to %s characters." % (adjective3, verb5))
print("In the game, you can play as characters like %s or %s." % (character, character2))
print(" Sadly, they didn’t add in %s." % character3)
print("There are lots of cool items too! There’s (a/an) %s, %s, %s and just to name a few." % (noun4, noun5, noun6))
print("Of course, when characters get the %s they can use a %s." % (noun7, noun8))
print("You shouldn't choose characters who are %s or %s. " % (adjective4, adjective5))
print("I heard that they might add %s, %s characters, %s or %s!" % (character4, adjective6, character5, character6))
print("I sure (don’t) hope they add %s from %s!" % (character6, game))
print("These games are really fun. I look forward to when they come out in %s weeks." % number)
print()
print("You sure wrote a funny story %s!" % your_name)
