print("The New Super Smash Bros")
print("Please no swearing and/or inappropriate words for a classroom")

person = input("Give me a name of person")
adjective = input("Adjective Time! Give me one!")
verb = input("Can you give me a verb?")
verb2 = input("Can you give me a second verb?")
noun = input("I'm gonna need a noun now.")
noun2 = input("I'm gonna need another noun")
pluralnoun = input("I need a plural noun next")
verb3 = input("Can I get a verb?")
noun3 = input("I need a third noun")
verb4 = input("I need a fourth verb now...")
adjective2 = input("I need a new adjective")
person2 = input("Give me another person name")
adjective3 = input("I need a third adjective")
verb5 = input("Wow, I need a fifth verb!")
character = input ("Give me a character from a game, book or show")
character2 = input ("Give me another character from a game, book or show")
character3 = input ("It's a triple wammy! Give me another character from a game, book or show")
noun4 = input("Time for a new noun")
noun5 = input("Can I get another noun?")
noun6 = input("Tic-tac-toe! 3 nouns in a row")
noun7 = input("...I need another noun...")
verb6 = input("Finally! A verb! (Give me one)")
adjective4 = input("I need an adjective now")
adjective5 = input("I need another adjective now")
character4 = input("Give me a character from a game, book or show")
adjective6 = input("New adjective! Go!")
character5 = input("Give me a new character from a game, book or show")
character6 = input("I need a new character now")
game = input("Give me some kind of video game")
number = input("Give me a number! Large or small, it doesn't matter!")
print()
print ("Time for the Mad Lib!")
print()
print()
print()
print()
print("Super Smash Bros is a game made by %s in which %s characters %s (with) each other." % (person, adjective, verb))
print("The objective is to %s each other off (the) %s." % (verb2, noun))
print("There are many modes like ____ where you fight to make characters lose _____")