print("Hangman! []____0-/-<")

Man = input("What is the name of the person who will be hung? ")
You = input("You are %s's last chance. What is your name? " % Man)
print()
print()
print("%s: Help!" % Man)
print()
print("Executioner: Hello sir/madam, what is your business here?")
print("%s: Don't hang %s!" % (You, Man))
print("Executioner: Hmmmm... Do my son's English homework, you gotta guess a word or something boring like that.")
print("Executioner: If you guess correctly, I'll let %s go " % Man)
print("Executioner: But for each letter you get wrong, I'll tighten this rope by a little bit")
print("%s: I'll do it!" % You)